server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name yoti.42.fr;

    ssl_certificate /etc/nginx/ssl/yoti.crt;
    ssl_certificate_key /etc/nginx/ssl/yoti.key;
    ssl_protocols TLSv1.3;

    root /var/www/html;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location /static/ {
        alias /var/www/html/public/;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass wordpress:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ ^/adminer(/.*)?$ {
        proxy_pass http://adminer:8080;
    }

    location /portainer/ {
        proxy_pass http://portainer:9000/;
    }
}
