services:
  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      - static-page
      - adminer
      - portainer
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    env_file:
      - .env

  static-page:
    container_name: static-page
    build:
      context: ./requirements/bonus/static_page
      dockerfile: Dockerfile
    restart: always
    networks:
      - network

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env
    secrets:
      - db_root_password
      - db_password
      - wp_second_password
      - adminer_password

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
    secrets:
      - db_root_password
      - db_password
      - wp_second_password
      - redis_password

  redis:
    container_name: redis
    build: ./requirements/bonus/redis
    restart: always
    env_file:
      - .env
    networks:
      - network
    secrets:
      - redis_password

  ftp_server:
    container_name: ftp_server
    build:
      context: ./requirements/bonus/ftp_server
      dockerfile: Dockerfile
    restart: always
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    env_file:
      - .env
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - ftp_password
    depends_on:
      - wordpress

  adminer:
    container_name: adminer
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - mariadb

  portainer:
    container_name: portainer
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    secrets:
      - portainer_password
    networks:
      - network

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  wp_second_password:
    file: ../secrets/wp_second_password.txt
  redis_password:
    file: ../secrets/redis_password.txt
  ftp_password:
    file: ../secrets/ftp_password.txt
  portainer_password:
    file: ../secrets/portainer_password.txt
  adminer_password:
    file: ../secrets/adminer_password.txt

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yrafai/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yrafai/data/wordpress
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yrafai/data/portainer
      o: bind

networks:
  network:
    driver: bridge
