services:
  nginx:
    container_name: nginx
    build: 
      context: ./srcs/requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
      - static-page
      - adminer
      - portainer
    ports:
      - 443:443
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    networks:
      - network
    env_file:
      - .env

  static-page:
    container_name: static-page
    build:
      context: ./srcs/requirements/bonus/static_page
      dockerfile: Dockerfile
    restart: always
    networks:
      - network
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build: ./srcs/requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network
    restart: always
    env_file:
      - .env

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: ./srcs/requirements/wordpress
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network

  redis:
    container_name: redis
    build: ./srcs/requirements/bonus/redis
    ports:
      - '6379:6379'
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - network
  
  ftp_server:
    container_name: ftp_server
    depends_on:
      - nginx
      - redis
    build:
      context: ./srcs/requirements/bonus/ftp_server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 21:21
      - 21100-21110:21100-21110
    env_file:
      - .env
    networks:
      - network
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - FTP_USER=${FTP_USER}
      - FTP_PASSWORD=${FTP_PASSWORD}

  adminer:
    container_name: adminer
    build:
      context: ./srcs/requirements/bonus/adminer
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - network
    depends_on:
      - mariadb

  portainer:
    container_name: portainer
    build:
      context: ./srcs/requirements/bonus/portainer
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:9000"
    environment:
      - TZ=Europe/Paris
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - network

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yoti/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yoti/data/wordpress
      o: bind
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/yoti/data/portainer
      o: bind

networks:
  network:
    driver: bridge